// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Convert WOFF2 bytes to TTF bytes.
///
/// This is a pure in-memory operation - no file I/O is performed.
///
/// # Arguments
/// * `woff2_data` - Raw WOFF2 font bytes (e.g., downloaded from server)
///
/// # Returns
/// * `Ok(Vec<u8>)` - TTF font bytes ready for FontLoader
/// * `Err(_)` - If WOFF2 decoding fails
///
/// # Example (Dart side)
/// ```dart
/// final ttfBytes = await convertWoff2ToTtf(woff2Data: woff2Bytes);
/// final fontLoader = FontLoader('MyFont');
/// fontLoader.addFont(Future.value(ByteData.view(ttfBytes.buffer)));
/// await fontLoader.load();
/// ```
Future<Uint8List> convertWoff2ToTtf({required List<int> woff2Data}) => RustLib
    .instance
    .api
    .crateApiFontConverterConvertWoff2ToTtf(woff2Data: woff2Data);

/// Find code points that map to zero-advance, empty glyphs in a TTF font.
///
/// These are effectively invisible placeholders in the obfuscation font.
/// Web rendering swallows them naturally, but Flutter may leave visible holes.
Future<Uint32List> extractInvisibleCodepoints({required List<int> ttfData}) =>
    RustLib.instance.api.crateApiFontConverterExtractInvisibleCodepoints(
      ttfData: ttfData,
    );
